# configs/ingestion.yaml
spark:
  app_name: "DataIngestionApp"
  s3a:
    access_key: "minioadmin"
    secret_key: "minioadmin123"
    endpoint: "http://minio:9000"
    path_style_access: "true"
    region: "us-east-1"
    impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"  # <--- Adicione esta linha

ingestion:
  years_months:
    2023: [1,2,3, 4, 5]
  input_bucket: "yellow-taxi-files"
  output_bucket: "prd-yellow-taxi-table"
  parquet_path: "year={year}/month={month}/yellow_tripdata.parquet"
parquet:
  bucket_bronze: "yellow-taxi-file-staging"     # Bucket onde o arquivo é salvo após o upload
  bucket_silver: "yellow-taxi-file"  
  bucket_gold: "prd-yellow-taxi-table"
  path: "year={year}/month={month}/yellow_tripdata.parquet"
